# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DVAAk7kDd2Sw_85RqMRch9A_f_cn3e6W
"""

from numpy.core.numerictypes import cast
import numpy as np
import os
import uuid


def generate_inspection(inspection_id, num_wave_arrays):

    """
    Generates an inspection with specified number of wave arrays and saves them to the local machine location
    Args:
        inspection_id (str): unique ID for the inspection
        num_wave_arrays (int): number of wave arrays to generate for the inspection
    """



    try:

      # Check if directory exist otherewise create a directory to save the wave arrays
      if not os.path.exists(inspection_id):
          os.makedirs(inspection_id)

      # generate and save the wave arrays
      for i in range(num_wave_arrays):
          # create a random 10kb numpy array
          wave_array = np.random.rand(10000)

          # save the array to the local machine by path inspection_id/"inspection_id_wave_array_number.npy"
          np.save(f"{inspection_id}/{inspection_id}_{i}.npy", wave_array) 

      print("Successfully generated and saved an inspection_id with ~50 wave arrays in directory {}".format(inspection_id))
    
    except:
        print("Something went wrong when saving the file")



        
# Example of assigning a unique ID 
inspection_id = str(uuid.uuid1().hex)[:5] # randomly generated unique id with limit of 5 characters.
num_wave_arrays = 50 # Number of wave arrays

# calling generate_inspection function.
generate_inspection(inspection_id, num_wave_arrays)

